name : "hello world workflow"

# Controls when the actions will run. Triggers the workflow on master or  production branch.

on :
    push:
     branches:
      - master 
      - production
jobs:
  hello_world:
   runs-on: ubuntu-latest
   steps:
    -name: Print Hello World
     run: echo "hello world"